export type UserRole = 'manager' | 'teacher';

export type UserStatus = 'active' | 'inactive' | 'leave' | 'resigned';

export interface User {
  id: string;
  teacherCode: string;
  fullName: string;
  username?: string;
  password?: string;
  email: string;
  phone: string;
  avatar: string;
  role: UserRole;
  position: string; // e.g. "Giáo viên Quản nhiệm KTX A", "Trưởng Bộ phận Nội trú"
  status: UserStatus;
  departmentId: string;
  employmentDate: string; // YYYY-MM-DD
  birthday: string;
  gender: 'nam' | 'nữ';
  address: string;
  nightShiftEligible: boolean;
  assignedRoomIds: string[];
  assignedStudentIds: string[];
  assignedBuilding?: string;
  workloadIndex: number; // e.g. 0.82 to 1.45 calculated from students & rooms count
}

export type SpecialLabel = 
  | 'mental_support'
  | 'academic_risk'
  | 'health_issue'
  | 'behavior_issue'
  | 'parent_request'
  | 'other';

export interface Student {
  id: string;
  studentCode: string;
  fullName: string;
  gender: 'nam' | 'nữ';
  birthday: string;
  className: string;
  roomId: string;
  roomName: string;
  teacherId: string;
  teacherName: string;
  parentName: string;
  parentPhone: string;
  status: 'active' | 'transferred' | 'graduated';
  specialCare: boolean;
  specialLabels: SpecialLabel[];
  healthNote?: string; // Tình trạng sức khỏe, bệnh lý, dị ứng
  note?: string; // Ghi chú chung của giáo viên
  lastInteractionDate?: string; // YYYY-MM-DD
  interactionCountThisMonth: number;
  uploadedByUserId?: string; // ID của tài khoản giáo viên tải lên / tạo học sinh
  uploadedByUserName?: string; // Tên giáo viên tải lên
}

export type HygieneStatus = 'pass' | 'needs_correction' | 'critical';

export interface Room {
  id: string;
  roomName: string;
  building: string; // e.g. "KTX A", "KTX B"
  floor: number;
  capacity: number;
  occupied: number;
  gender: 'nam' | 'nữ';
  teacherId: string;
  teacherName: string;
  status: 'clean' | 'pending' | 'dirty';
  hygieneStatus: HygieneStatus;
  lastInspectedAt?: string;
  correctionNote?: string;
}

export type ShiftType = 'morning' | 'lunch' | 'afternoon' | 'evening' | 'night' | 'weekend';

export interface Position {
  id: string;
  positionCode: string;
  positionName: string;
  description: string;
  building?: string;
  floor?: number;
  requiredTeachers: number;
  priority: 'low' | 'medium' | 'high' | 'critical';
}

export interface ScheduleTemplate {
  id: string;
  templateName: string; // "Ngày thường", "Cuối tuần", "Ngày Lễ"
  dayType: 'weekday' | 'weekend' | 'holiday';
  shift: ShiftType;
  startTime: string; // "06:00"
  endTime: string;   // "07:30"
  positions: {
    positionId: string;
    positionName: string;
    startTime: string;
    endTime: string;
    requiredTeachers: number;
  }[];
}

export type ScheduleAssignmentStatus = 'scheduled' | 'working' | 'completed' | 'swapped' | 'absent' | 'verified' | 'rejected';

export interface ScheduleAssignment {
  id: string;
  date: string; // YYYY-MM-DD
  teacherId: string;
  teacherName: string;
  teacherCode: string;
  shift: ShiftType;
  templateId: string;
  positionId: string;
  positionName: string;
  roomIds: string[];
  status: ScheduleAssignmentStatus;
  swapWithTeacherId?: string;
  swapApprovedBy?: string;
  swapNote?: string;
  completedAt?: string;
  completionNote?: string;
  proofPhotos?: string[];
  evaluationStatus?: 'pending_review' | 'approved' | 'rejected';
  evaluationCriteria?: string;
  deductedPoints?: number;
  evaluationNote?: string;
  evaluatedBy?: string;
  evaluatedAt?: string;
}

export type TaskCategory = 'core' | 'routine' | 'additional' | 'emergency';

export interface TaskTemplate {
  id: string;
  taskCode: string;
  taskName: string;
  taskCategory: TaskCategory;
  shift: ShiftType;
  priority: 'low' | 'medium' | 'high' | 'critical';
  needPhoto: boolean;
  needNote: boolean;
  autoGenerated: boolean;
  scoreWeight: number; // Base points e.g. 5
  timeOffsetStart?: string; // "06:00"
  timeOffsetEnd?: string;   // "06:45"
  description: string;
}

export type TaskStatus = 'pending' | 'working' | 'completed' | 'late' | 'skipped' | 'cancelled' | 'verified' | 'rejected';

export interface TaskInstance {
  id: string;
  taskCode: string;
  taskName: string;
  title?: string;
  taskCategory: TaskCategory;
  shift: ShiftType;
  teacherId: string;
  teacherName: string;
  date: string; // YYYY-MM-DD
  scheduleAssignmentId?: string;
  plannedStart: string; // "06:00"
  plannedEnd: string;   // "06:45"
  actualStart?: string;
  actualEnd?: string;
  status: TaskStatus;
  roomId?: string;
  roomName?: string;
  studentId?: string;
  studentName?: string;
  score: number;
  verified: boolean;
  verifiedBy?: string;
  verifiedAt?: string;
  note?: string;
  proofPhotos?: string[];
  priority: 'low' | 'medium' | 'high' | 'critical';
  evaluationCriteria?: string;
  deductedPoints?: number;
  evaluationNote?: string;
}

export interface Interaction1on1 {
  id: string;
  teacherId: string;
  teacherName: string;
  studentId: string;
  studentName: string;
  className: string;
  roomName: string;
  interactionDate: string; // YYYY-MM-DD
  startTime: string; // "19:30"
  endTime: string;   // "20:00"
  durationMinutes: number;
  location: string; // e.g. "Phòng Quản nhiệm Tầng 2", "Góc sinh hoạt chung"
  topic: string;
  summary: string;
  observation: string;
  supportPlan: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  followUpDate?: string;
  followUpStatus?: 'pending' | 'done';
  attachments?: string[];
  createdAt: string;
}

export interface KPIRecord {
  id: string;
  teacherId: string;
  teacherName: string;
  teacherCode: string;
  date: string; // YYYY-MM-DD
  operationScore: number;    // Max 50
  qualityScore: number;      // Max 20
  studentCareScore: number;  // Max 15
  contributionScore: number; // Max 10
  disciplineScore: number;   // Max 5 (starts at 5, deductions applied)
  totalScore: number;        // Sum of above (Max 100)
  rank: 'A+' | 'A' | 'B' | 'C' | 'D';
  workloadIndex: number;
  tasksCompleted: number;
  tasksTotal: number;
  interactionsCompletedThisWeek: number;
  penalties: {
    reason: string;
    pointsDeducted: number;
    time: string;
  }[];
}

export interface DailyEvaluation {
  id: string;
  date: string; // YYYY-MM-DD
  teacherId: string;
  teacherName: string;
  teacherCode: string;
  evaluatorId: string;
  evaluatorName: string; // "Thầy Lê Huy Phúc"
  evaluatedAt: string;
  operationScore: number;    // Max 50
  qualityScore: number;      // Max 20
  studentCareScore: number;  // Max 15
  contributionScore: number; // Max 10
  disciplineScore: number;   // Max 5
  totalScore: number;        // Max 100
  rank: 'A+' | 'A' | 'B' | 'C' | 'D';
  strengths?: string;
  improvements?: string;
  generalComment: string;
  status: 'evaluated';
}

export interface NotificationItem {
  id: string;
  receiverId: string; // Teacher ID or 'all' or 'manager'
  title: string;
  content: string;
  type: 'shift' | 'task' | 'interaction' | 'kpi' | 'emergency' | 'system';
  priority: 'low' | 'medium' | 'high' | 'critical';
  read: boolean;
  createdAt: string;
  linkUrl?: string;
}

export interface AuditLog {
  id: string;
  userId: string;
  userName: string;
  userRole: UserRole;
  module: string;
  operation: string;
  details: string;
  oldData?: string;
  newData?: string;
  timestamp: string;
}

export interface DepartmentSettings {
  departmentName: string;
  schoolName: string;
  academicYear: string;
  currentSemester: string;
  currentWeek: number;
  minInteractionsPerWeek: number;
  maxInteractionsPerWeek: number;
  shiftTimes: {
    morningStart: string;
    morningEnd: string;
    lunchStart: string;
    lunchEnd: string;
    afternoonStart: string;
    afternoonEnd: string;
    eveningStart: string;
    eveningEnd: string;
    nightStart: string;
    nightEnd: string;
  };
  kpiWeights: {
    operation: number;    // 50
    quality: number;      // 20
    studentCare: number;  // 15
    contribution: number; // 10
    discipline: number;   // 5
  };
}

// Báo cáo Công việc Hằng ngày & Tình trạng Học sinh (Bắt buộc có Mã HS) + Phòng KTX
export interface StudentIncidentReport {
  id: string;
  studentCode: string; // YÊU CẦU: BẮT BUỘC CÓ MÃ HS
  studentName: string;
  className: string;
  roomName: string;
  category: 'health' | 'mental' | 'discipline' | 'absence' | 'other';
  severity: 'emergency' | 'warning' | 'normal';
  incidentDetail: string; // Chi tiết tình trạng học sinh
  initialActionTaken: string; // Biện pháp đã xử lý ban đầu của GVQN
  handled: boolean; // Admin/Bộ phận đã tiếp nhận và xử lý
}

export interface RoomConditionReport {
  id: string;
  roomName: string; // Phòng KTX (ví dụ: DomB-101, Phòng 301...)
  building?: string;
  hygieneStatus: 'good' | 'average' | 'poor'; // Tình trạng vệ sinh
  facilityIssues?: string; // Hư hỏng trang thiết bị (quạt, đèn, điện nước, giường...)
  disciplineStatus?: string; // Nền nếp phòng KTX, ồn ào...
  severity: 'critical' | 'warning' | 'normal'; // Cảnh báo phòng
  handled: boolean;
}

export interface DailyWorkReport {
  id: string;
  date: string; // YYYY-MM-DD
  shift: 'morning' | 'noon' | 'afternoon' | 'evening' | 'night' | 'fullday';
  teacherId: string;
  teacherName: string;
  teacherCode: string;
  createdAt: string;

  // 1. Tình trạng công việc ca trực
  tasksCompletionRate: number; // 0 - 100%
  completedTasksCount: number;
  totalTasksCount: number;
  workStatus: 'completed' | 'in_progress' | 'issues_pending';
  workSummary: string; // Tóm tắt công việc đã thực hiện
  handoverNotes?: string; // Ghi chú bàn giao ca sau
  suggestionsToManager?: string; // Khó khăn, kiến nghị với Admin Thầy Lê Huy Phúc

  // 2. Tình trạng học sinh trong ngày (BẮT BUỘC CÓ MÃ HS)
  studentIncidents: StudentIncidentReport[];

  // 3. Tình trạng phòng KTX
  roomConditions: RoomConditionReport[];

  // 4. Chỉ đạo & Phản hồi của Admin (Thầy Lê Huy Phúc)
  adminFeedback?: string;
  adminFeedbackAt?: string;
  adminReviewed: boolean;
}
